package io.github.xibalbaM.j2datapack;

import io.github.xibalbaM.j2datapack.commands.ICommand;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;

public class McFunction extends NamespacePart {

    private List<ICommand> commands = new ArrayList<>();

    public McFunction(String name) {

        super(name);
    }

    @Contract("_ -> new")
    public static @NotNull McFunction of(String name) {
        return new McFunction(name);
    }

    @Override
    public String generateContent() {

        StringBuilder builder = new StringBuilder("# Generated by j2datapack\n");

        for (ICommand command : commands) {

            builder.append(command.getCommand()).append("\n");
        }

        return builder.toString();
    }

    public McFunction command(ICommand command) {

        commands.add(command);
        return this;
    }
}
